defaults:

  update-submodules: &update-submodules
    run:
      name: "Update git submodules"
      command: git submodule update --init --depth 30

  upload-hunter-cache: &upload-hunter-cache
    run:
      name: "Upload Hunter cache"
      command: |  # Upload Hunter cache if not PR build.
        if [ ! "$CIRCLE_PR_NUMBER" ]; then
          cmake --build build --target hunter_upload_cache
        fi

  configure: &configure
    run:
      name: "Configure"
      command: |
        mkdir -p build && cd build
        cmake .. -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOVERAGE=ON $CMAKE_OPTIONS
        echo $CXX > compiler

  build: &build
    run:
      name: "Build"
      command: cmake --build build -- -j $BUILD_PARALLEL_JOBS

  test: &test
    run:
      name: "Test"
      pwd: build
      command: |
        if [ $(uname) = Linux ]; then
          export TMPDIR=/dev/shm
        fi
        export ETHEREUM_TEST_PATH=~/project/test/jsontests
        ctest -j8 --output-on-failure

  store-eth: &store-eth
    store_artifacts:
      path: build/eth/eth
      destination: eth

  save-deps-cache: &save-deps-cache
    cache-save:
      name: "Save dependencies cache"
      key: &deps-cache-key deps-1-{{arch}}-{{checksum "build/compiler"}}-{{checksum "cmake/ProjectJsonRpcCpp.cmake"}}
      paths:
        - build/deps

  restore-deps-cache: &restore-deps-cache
    cache-restore:
      name: "Restore dependencies cache"
      key: *deps-cache-key

  save-ethash-dag: &save-ethash-dag
    cache-save:
      name: "Save Ethash DAG file"
      key: &ethash-dag-key ethash-dag0-{{arch}}
      paths:
        - ~/.ethash/full-R23-0000000000000000

  restore-ethash-dag: &restore-ethash-dag
    cache-restore:
      name: "Restore Ethash DAG file"
      key: *ethash-dag-key

  linux-steps: &linux-steps
    - checkout
    - *update-submodules
    - *configure
    - *upload-hunter-cache
    - *restore-deps-cache
    - *build
    - *save-deps-cache
    - *store-eth
    - *restore-ethash-dag
    - *test
    - *save-ethash-dag

    - run:
        name: "Code coverage"
        pwd: build
        command: |
          bash <(curl -s https://codecov.io/bash) -X fix

version: 2
jobs:

  Linux-Clang5:
    environment:
      - CXX: clang++-5.0
      - CC:  clang-5.0
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 8
    docker:
      - image: ethereum/cpp-build-env
    steps: *linux-steps

  Linux-GCC6-ASan:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++-6
      - CC:  gcc-6
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DSANITIZE=address
    docker:
      - image: ethereum/cpp-build-env
    steps: *linux-steps

  macOS-XCode9:
    environment:
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 8
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - *update-submodules
      - run:
          name: "Install macOS dependencies"
          command: |
            pip install -q requests &
            HOMEBREW_NO_AUTO_UPDATE=1 brew install -q cmake ninja leveldb libmicrohttpd &
            wait
      - *configure
      - *upload-hunter-cache
      - *restore-deps-cache
      - *build
      - *save-deps-cache
      - *store-eth
      - *restore-ethash-dag
      - *test
      - *save-ethash-dag
      - run:
          name: "Upload coverage data"
          pwd: build
          command: codecov

# TODO: Run GCC6 build only in develop branch.
# TODO: Enabled nightly builds and add more configs.
# TODO: Separate builds from testing jobs.
workflows:
  version: 2
  cpp-ethereum:
    jobs:
      - macOS-XCode9
      - Linux-Clang5
      - Linux-GCC6-ASan
